replicasCount: 1
fullName: "platform-ms-keys"
selectorLabel: "platform-ms-keys"
domain : "keys.solenopsys.org"

service:
  port: 8080

storage:
  data:
    volumeName: keys-db-vol
    storageSize: 1Gi
    accessModes: "ReadWriteOnce"

container:
  name: server
  image: registry.solenopsys.org/platform-ms-keys
  pullPolicy: Always

uiHost: "solenopsys.org"

smtpServer:
  host: "solenopsys-mail.svc.cluster.local"
  port: 8587


successRedirect: "/login"
errorRedirect: "/session-not-found"